services:
  - type: web
    name: telegram-support-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-bot-db
          property: connectionString
      - key: WEBHOOK_URL
        sync: false
      - key: UPLOAD_PATH
        value: /opt/render/project/src/uploads
      - key: PORT
        value: 10000
    healthCheckPath: /

databases:
  - name: telegram-bot-db
    plan: free
    databaseName: telegram_bot
    user: telegram_bot
